// Code generated by "stringer -type=Water"; DO NOT EDIT

package main

import "fmt"

const _Water_name = "IrohasuVolvicCrystalGeyserAlcaliIonWaterPerrierContrexWilkinsonAmebaWaterOnsensui"

var _Water_index = [...]uint8{0, 7, 13, 26, 40, 47, 54, 63, 73, 81}

func (i Water) String() string {
	if i < 0 || i >= Water(len(_Water_index)-1) {
		return fmt.Sprintf("Water(%d)", i)
	}
	return _Water_name[_Water_index[i]:_Water_index[i+1]]
}
